name: 'GitHub Action for GraalVM'
github-token:
  action-input:
    input: token
    is-default: false
  permissions:
    issues: write
    issues-reason: to <reason_here> # specify why issues is used.